-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwA35pnpJKoJyT4AH
gVE3LZmQWbojmFwFqIiZ+Epgq7igCgYIKoZIzj0DAQehRANCAAS0glcGEg4OiFaN
m9YccFNz3oDpI2I+Ze5zVdyKhwFMTLW5jkI3P7h/gktgGcBNsvwtjEycXvkK+cZ/
4YsHTHa/
-----END PRIVATE KEY-----